### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 1382: ordinal not in range(128)

### ISSUE THREAD

**Issue by abhay2703** [metrixplusplus/metrixplusplus#43]
Hello,

I am using python2.7 on CentOS8.2

I am getting the below error:

Traceback (most recent call last):
  File "/usr/bin/metrix++", line 11, in <module>
    load_entry_point('metrixpp==1.6.2', 'console_scripts', 'metrix++')()
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/metrixpp.py", line 38, in start
    exit_code = main()
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/metrixpp.py", line 30, in main
    exit_code = loader.run(args)
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/mpp/internal/loader.py", line 206, in run
    exit_code += item.run(args)
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/ext/std/tools/collect.py", line 84, in run
    return self.reader.run(self, "./")
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/ext/std/tools/collect.py", line 208, in run
    total_errors = run_recursively(plugin, directory)
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/ext/std/tools/collect.py", line 199, in run_recursively
    exit_code += run_per_file(plugin, fname, full_path)
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/ext/std/tools/collect.py", line 147, in run_per_file
    exit_code += run_recursively(plugin, full_path)
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/ext/std/tools/collect.py", line 199, in run_recursively
    exit_code += run_per_file(plugin, fname, full_path)
  File "/usr/lib/python2.7/site-packages/metrixpp-1.6.2-py2.7.egg/metrixpp/ext/std/tools/collect.py", line 169, in run_per_file
    checksum = binascii.crc32(text.encode('utf8')) & 0xffffffff # to match python 3
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 1382: ordinal not in range(128)

The file that is giving error:
$ file ./test/test_cc.cpp
./test/test_cc.cpp: C source, Non-ISO extended-ASCII text

**Comment by avkonst** [comment]
I am afraid not much can be done about it. Is converting the file to utf-8 helps?

**Comment by abhay2703** [comment]
Converting the file to 'utf-8' is changing some characters in the file, so I was trying to avoid file conversion.

**Comment by avkonst** [comment]
Than the only option is to exclude the file from the analysis...

**Comment by abhay2703** [comment]
I have another question - off topic:
Is the tool tested for python3.x ?

As this issue is not observed while using python3

**Comment by avkonst** [comment]
Yes, this tool is tested with python3 too. I think you should be able to
see the github actions executed on commit and release. It has got a number
of platforms and python versions tested.

**Comment by abhay2703** [comment]
Now, I am facing this issue with metrix++ installation on python3.6:

Traceback (most recent call last):
  File "/usr/local/bin/metrix++", line 11, in <module>
    load_entry_point('metrixpp==1.6.2', 'console_scripts', 'metrix++')()
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/metrixpp.py", line 38, in start
    exit_code = main()
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/metrixpp.py", line 30, in main
    exit_code = loader.run(args)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/mpp/internal/loader.py", line 206, in run
    exit_code += item.run(args)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 84, in run
    return self.reader.run(self, "./")
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 210, in run
    total_errors = run_recursively(plugin, directory)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 201, in run_recursively
    exit_code += run_per_file(plugin, fname, full_path)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 147, in run_per_file
    exit_code += run_recursively(plugin, full_path)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 201, in run_recursively
    exit_code += run_per_file(plugin, fname, full_path)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 147, in run_per_file
    exit_code += run_recursively(plugin, full_path)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 201, in run_recursively
    exit_code += run_per_file(plugin, fname, full_path)
  File "/usr/local/lib/python3.6/site-packages/metrixpp-1.6.2-py3.6.egg/metrixpp/ext/std/tools/collect.py", line 156, in run_per_file
    text = f.read();
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 1973: invalid start byte

**Comment by avkonst** [comment]
Looks like the file is not utf8 .... Not sure what we can do about it

**Comment by huornlmj** [comment]
I have this issue too and I wanted to exclude the file causing the issue, but I cannot identify the file name to exclude from the error.  Any suggestions as to how?

**Comment by huornlmj** [comment]
BTW - this only happens to me when using the version installed with pip.  It works file if I just clone the metrix++ repo and use the command from there.  Same version of Python (Python 3.6.9).  Sadly metrix++ does not have a version switch so I cannot tell you which version comes from pip.

**Comment by brodym** [comment]
I had a similar problem...I started by deleting comments and unnecessary code from my files which resolved some of these errors, but I finally got annoyed enough to dig deeper.  The problem *seems* to be that the code in collect.py is unsuccessful at obtaining the correct file encoding.  Below is modified code that I used to successfully avoid all the unicode related errors I was originally getting when trying to process my source files which were of "Western European (Windows)" encoding:

```
                        try:
                           text = text.encode(f.encoding)
                        except:
                            pass
                        try:
                            text = text.decode('**windows-1252**')
                        except:
                            pass
                        f.close()
                        checksum = binascii.crc32(text.encode('utf8')) & 0xffffffff # to match python 3
```
to be clear I changed the decoding attempt which was originally UTF-8 to be windows-1252.  It's clear to me this is the code that is causing people fits (and a comment seems to even acknowledge it was causing fits to get unit tests working).  I still very much consider my fix to very much be a hack...I suspect the following link has resources that can lead someone to a "real fix": https://stackoverflow.com/questions/11544541/python-ascii-and-unicode-decode-error.  In the meantime, perhaps my hack below will help others (note, you should verify your actual file encoding which I did via emeditor).

**Comment by avkonst** [comment]
ohh, this is getting nowhere taking into account how many encodings exist... is not it easier to convert sources to utf-8?

**Comment by avkonst** [comment]
Maybe I need to release the latest metrix++ to pip..

**Comment by prozessorkern** [comment]
Just released a new version on pypi - this includes the mentioned fixes - hope this fixes your issues.
